kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: gokhantst
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: rails-pgsql-persistent-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-mirror
  volumeMode: Filesystem